"""add consultation fee to emr doctor profiles

Revision ID: 1462660fbf8c
Revises: 23cabc12aa4a
Create Date: 2026-10-02 20:03:33.832379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1462660fbf8c'
down_revision: Union[str, None] = '23cabc12aa4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emr_doctor_profiles', sa.Column('consultation_fee_paise', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emr_doctor_profiles', 'consultation_fee_paise')
    # ### end Alembic commands ###
