"""add patient billing tables

Revision ID: 23cabc12aa4a
Revises: 3c734b0950bb
Create Date: 2026-10-02 20:00:41.762355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23cabc12aa4a'
down_revision: Union[str, None] = '3c734b0950bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pb_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_uhid', sa.String(length=30), nullable=True),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('counter', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='issued', nullable=False),
    sa.Column('gross_paise', sa.Integer(), nullable=False),
    sa.Column('discount_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('net_paise', sa.Integer(), nullable=False),
    sa.Column('paid_paise', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'invoice_number', name='uq_pb_invoices_number')
    )
    op.create_index('idx_pb_invoices_patient', 'pb_invoices', ['pharmacy_id', 'patient_id'], unique=False)
    op.create_index('idx_pb_invoices_status', 'pb_invoices', ['pharmacy_id', 'status'], unique=False)
    op.create_table('pb_charge_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_uhid', sa.String(length=30), nullable=True),
    sa.Column('source_module', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('encounter_ref', sa.String(length=100), nullable=True),
    sa.Column('encounter_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='unbilled', nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=150), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['pb_invoices.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pb_charge_items_invoice', 'pb_charge_items', ['invoice_id'], unique=False)
    op.create_index('idx_pb_charge_items_patient', 'pb_charge_items', ['pharmacy_id', 'patient_id', 'status'], unique=False)
    op.create_index('uq_pb_charge_items_key', 'pb_charge_items', ['pharmacy_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('pb_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['pb_invoices.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'receipt_number', name='uq_pb_payments_receipt')
    )
    op.create_index('idx_pb_payments_day', 'pb_payments', ['pharmacy_id', 'paid_on'], unique=False)
    op.create_index('idx_pb_payments_invoice', 'pb_payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pb_payments_invoice', table_name='pb_payments')
    op.drop_index('idx_pb_payments_day', table_name='pb_payments')
    op.drop_table('pb_payments')
    op.drop_index('uq_pb_charge_items_key', table_name='pb_charge_items', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('idx_pb_charge_items_patient', table_name='pb_charge_items')
    op.drop_index('idx_pb_charge_items_invoice', table_name='pb_charge_items')
    op.drop_table('pb_charge_items')
    op.drop_index('idx_pb_invoices_status', table_name='pb_invoices')
    op.drop_index('idx_pb_invoices_patient', table_name='pb_invoices')
    op.drop_table('pb_invoices')
    # ### end Alembic commands ###
