"""add emr settings, doctor profiles and patient uhid

Revision ID: 3c734b0950bb
Revises: dc6a0865f1a9
Create Date: 2026-10-02 17:35:22.331659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c734b0950bb'
down_revision: Union[str, None] = 'dc6a0865f1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emr_doctor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'user_id', name='uq_emr_doctor_profiles_user')
    )
    op.create_table('emr_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('clinic_address', sa.Text(), nullable=True),
    sa.Column('clinic_phone', sa.String(length=20), nullable=True),
    sa.Column('clinic_email', sa.String(length=200), nullable=True),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('rx_footer', sa.Text(), nullable=True),
    sa.Column('rx_prefix', sa.String(length=10), server_default='RX-', nullable=False),
    sa.Column('uhid_prefix', sa.String(length=10), server_default='UH-', nullable=False),
    sa.Column('uhid_digits', sa.Integer(), server_default='6', nullable=False),
    sa.Column('uhid_next', sa.Integer(), server_default='1', nullable=False),
    sa.Column('default_slot_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('patient_form', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id')
    )
    op.add_column('emr_patients', sa.Column('uhid', sa.String(length=30), nullable=True))
    # Give every existing patient a UHID (oldest first, per clinic) before uniqueness is enforced.
    # The settings row created on first use continues numbering after them (settings_service.py).
    op.execute("""
        UPDATE emr_patients p SET uhid = 'UH-' || lpad(s.n::text, 6, '0')
        FROM (SELECT id, row_number() OVER (PARTITION BY pharmacy_id ORDER BY created_at, id) AS n
              FROM emr_patients) s
        WHERE p.id = s.id AND p.uhid IS NULL
    """)
    op.create_index('uq_emr_patients_uhid', 'emr_patients', ['pharmacy_id', 'uhid'], unique=True, postgresql_where=sa.text('uhid IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_emr_patients_uhid', table_name='emr_patients', postgresql_where=sa.text('uhid IS NOT NULL'))
    op.drop_column('emr_patients', 'uhid')
    op.drop_table('emr_settings')
    op.drop_table('emr_doctor_profiles')
    # ### end Alembic commands ###
