"""add emr prescriptions and prescription items

Revision ID: dc6a0865f1a9
Revises: ecd85336d185
Create Date: 2026-10-02 15:01:15.065842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc6a0865f1a9'
down_revision: Union[str, None] = 'ecd85336d185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emr_prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_user_id', sa.UUID(), nullable=False),
    sa.Column('rx_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('complaints', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['emr_appointments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['emr_patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'rx_number', name='uq_emr_prescriptions_number')
    )
    op.create_index('idx_emr_prescriptions_patient', 'emr_prescriptions', ['patient_id'], unique=False)
    op.create_index('idx_emr_prescriptions_pharmacy', 'emr_prescriptions', ['pharmacy_id'], unique=False)
    op.create_index('uq_emr_prescriptions_appointment', 'emr_prescriptions', ['appointment_id'], unique=True, postgresql_where=sa.text("status <> 'cancelled' AND deleted_at IS NULL"))
    op.create_table('emr_prescription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('medicine_name', sa.String(length=300), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['emr_prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emr_prescription_items_name', 'emr_prescription_items', ['pharmacy_id', 'medicine_name'], unique=False)
    op.create_index('idx_emr_prescription_items_rx', 'emr_prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_emr_prescription_items_rx', table_name='emr_prescription_items')
    op.drop_index('idx_emr_prescription_items_name', table_name='emr_prescription_items')
    op.drop_table('emr_prescription_items')
    op.drop_index('uq_emr_prescriptions_appointment', table_name='emr_prescriptions', postgresql_where=sa.text("status <> 'cancelled' AND deleted_at IS NULL"))
    op.drop_index('idx_emr_prescriptions_pharmacy', table_name='emr_prescriptions')
    op.drop_index('idx_emr_prescriptions_patient', table_name='emr_prescriptions')
    op.drop_table('emr_prescriptions')
    # ### end Alembic commands ###
