"""add emr patients, doctor schedules, appointments

Revision ID: ecd85336d185
Revises: e3511cb2db2b
Create Date: 2026-10-02 13:02:49.087246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd85336d185'
down_revision: Union[str, None] = 'e3511cb2db2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emr_doctor_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('doctor_user_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emr_doctor_schedules_doctor', 'emr_doctor_schedules', ['pharmacy_id', 'doctor_user_id', 'weekday'], unique=False)
    op.create_table('emr_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('alternate_phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='emr', nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emr_patients_customer', 'emr_patients', ['customer_id'], unique=False)
    op.create_index('idx_emr_patients_name', 'emr_patients', ['pharmacy_id', 'name'], unique=False)
    op.create_index('idx_emr_patients_pharmacy', 'emr_patients', ['pharmacy_id'], unique=False)
    op.create_index('idx_emr_patients_phone', 'emr_patients', ['pharmacy_id', 'phone'], unique=False)
    op.create_table('emr_appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_user_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='booked', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['emr_patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'doctor_user_id', 'appointment_date', 'token_number', name='uq_emr_appointments_token')
    )
    op.create_index('idx_emr_appointments_day', 'emr_appointments', ['pharmacy_id', 'appointment_date'], unique=False)
    op.create_index('idx_emr_appointments_patient', 'emr_appointments', ['patient_id'], unique=False)
    op.create_index('uq_emr_appointments_slot', 'emr_appointments', ['pharmacy_id', 'doctor_user_id', 'appointment_date', 'start_time'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND start_time IS NOT NULL AND status NOT IN ('cancelled', 'no_show')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_emr_appointments_slot', table_name='emr_appointments', postgresql_where=sa.text("deleted_at IS NULL AND start_time IS NOT NULL AND status NOT IN ('cancelled', 'no_show')"))
    op.drop_index('idx_emr_appointments_patient', table_name='emr_appointments')
    op.drop_index('idx_emr_appointments_day', table_name='emr_appointments')
    op.drop_table('emr_appointments')
    op.drop_index('idx_emr_patients_phone', table_name='emr_patients')
    op.drop_index('idx_emr_patients_pharmacy', table_name='emr_patients')
    op.drop_index('idx_emr_patients_name', table_name='emr_patients')
    op.drop_index('idx_emr_patients_customer', table_name='emr_patients')
    op.drop_table('emr_patients')
    op.drop_index('idx_emr_doctor_schedules_doctor', table_name='emr_doctor_schedules')
    op.drop_table('emr_doctor_schedules')
    # ### end Alembic commands ###
